"""update models 1

Revision ID: 0da52febc068
Revises: 7dbf222063e7
Create Date: 2025-08-30 15:54:53.351526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da52febc068'
down_revision: Union[str, Sequence[str], None] = '7dbf222063e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('courses_teacherId_fkey'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'teachers', ['teacher_id'], ['id'])
    op.drop_column('courses', 'teacherId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('teacherId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_teacherId_fkey'), 'courses', 'teachers', ['teacherId'], ['id'])
    op.drop_column('courses', 'teacher_id')
    # ### end Alembic commands ###
